### ISSUE TITLE
Enlace a la publicación del proyecto

### ISSUE THREAD

**Issue by edd885** [edd885/Tecnicas-de-machine-learning-en-an-lisis-de-resultados-de-laboratorio#1]
Publicación del proyecto en la plataforma LinkedIn

[https://www.linkedin.com/feed/update/urn:li:activity:7253948961156169728/](url)

Gracias por leer el contenido.

**Comment by edd885** [comment]
Se compartió el link. 
Se cierra issue, ya que esa fue la única razón para abrirlo.

**Comment by vcuspinera** [comment]
Gracias por compartir la liga a la publicación de divulgación de tu proyecto, estimado Eduardo.
Saludos, Víctor
