### ISSUE TITLE
Comentarios sobre proyecto EDA

### ISSUE THREAD

**Issue by vcuspinera** [edd885/Tecnicas-de-machine-learning-en-an-lisis-de-resultados-de-laboratorio#2]
Estimado Eduardo.
De forma global veo bien tu proyecto: el repositorio tiene la estructura es adecuada, realizaste el análisis en un Jupyter notebook, divulgaste tu proyecto a través de LinkedIn y añadiste la liga en un *issue* del proyecto, y cumpliste con la fecha de entrega. A continuación te comparto mis comentarios para algunas secciones, con mayor detalle.

### Estructura del repositorio
La estructura es adecuada y seguiste las recomendaciones del *paper* [Good Enough Practices in Scientific Computing](https://github.com/vcuspinera/UDG_MCD_Project_Dev_I/blob/main/actividades/material/02%20Good%20Enough%20Practices%20Sc%20Computing.pdf).

Consideraste las carpetas requeridas, considerando un archivo README file en cada una, así como los archivos para citar tu repositorio, contribución y licencia.

En el README de la carpeta raíz, el título del proyecto es “ML_in_laboratory”, te recomendaría que lo cambiaras por un título más descriptivo

En el archivo de referencia para que citen tu repositorio me llama la atención que el repositorio lo llames "EDA & ETL for epigenetics" y no "Técnicas de machine learning en análisis de resultados de laboratorio".

El diagrama de la estructura te quedó bien aunque hubieras podido ser más específico y añadir, al menos, los archivos más relevantes de cada carpeta, como el nombre del Jupyter notebook con el análisis EDA.

### `src`
En esta carpeta me gustó que incluyeras una prevé descripción del contenido, uso e instrucciones para correr el Jupyter notebook con tu análisis.

### Ortografía
Encontré muy pocas cosa que corregir relacionadas con la ortografía o gramática, por ejemplo, en la Justificación, ver carpeta `doc`, escribiste "Unas de las posibles aplicaciones que puede tener en ramo de la salud son, pero no se limitan a, son" y me parece que debería decir "Unas de las posibles aplicaciones que puede tener **el** ramo de la salud son, pero no se limitan a ~~, son~~:"; en esa misma sección para los enunciados de los *bullets points* siguientes te recomendaría que fueras consistente ya sea usando punto o eliminándolo al final de cada enunciado

### Análisis EDA
Corrí el código de tu notebook para buscar replicar tus resultados y estos son los comentarios que fueron surgiendo a lo largo de correr el código:

Me parece excelente que le hayas dedicado al inicio un espacio con la información general personal y una sección con la introducción a tu proyecto 😎 

También está muy bien que al inicio concentres las librerías que utilizarás a lo largo del notebook para el análisis.

Al leer los datos, utilizas una **ruta absoluta** y esto genera problemas a quien quiera replicar el análisis, te recomiendo utilizar una **ruta relativa** de acuerdo a la estructura de tu repositorio, es decir, en vez de usar el siguiente path para leer tu data:
```
file_path = r"C:\Users\eduar\Desktop\lab_analysis_github.xlsx"
```

…utiliza el siguiente:
```
file_path = r"../data/lab_analysis_github.xlsx"
```

En las visualizaciones, para el plot de distribución de datos te recomendaría que las barras las hicieras más anchas, y que la altura máxima del eje ‘y’ fuera similar en todas las gráficas para poder compararlas más fácilmente de forma visual. Además, ya que el `0` representa normalidad en el paciente y `1` representa que no es saludable, en estas gráficas podría ponerse en color azul o verde la barra del `0` y en rojo la barra del `1`, para ligar esta condición de saludable y no saludable con el color.

En algunas partes hablas de "columnas", pero para poder entenderlo mejor en el contexto del análisis médico podrías cambiarlo por variables, exámenes médicos o mediciones (de acuerdo a lo que consideres más adecuado.

Cuando hablas de sumas de valores, sería bueno que explicaras ya sea al principio o al final lo que significa, que por lo que entiendo habla del número de personas que tienen una condición no saludable para cada una de las variables/mediciones, de un total de 61 participantes. Por lo mismo, también podrías utilizar porcentajes respecto a tu muestra.

Cuando hablas de filas te recomendaría que lo cambiaras por pacientes, por lo que en el título de las visualizaciones "Condiciones de salud por fila (paciente)" recomendaría cambiarlo por "Condiciones de salud por paciente (filas)", y mencionar a los "pacientes 17, 25, …"

En la *Segmentación de los datos* me parece que haces un buen trabajo describiendo los grupos de pacientes.

Me da gusto que también trabajaste con Altair para familiarizarte con esta herramienta de visualización de datos.

En la sección de “Generación de pares en una matríz de correlación” no es necesario volver a llamar a las librerías de pandas, seaborn y matplotlib ya que lo hiciste al principio del notebook.

Me gustó la explicación que diste en la última sección sobre el dendograma, sería bueno que integraras una breve descripción del resultado del dendograma, aunque sea únicamente de forma descriptiva.

### Resultados
Te recomendaría incluir en el README las gráficas que guardaste en esa carpeta ya que aunque las mencionas es bueno mostrarlo directamente en el documento:

<img width="468" alt="image" src="https://github.com/user-attachments/assets/053a8844-14a2-473f-bbaf-c307680f6131">

### Comentarios finales
Me pareció bastante bueno el análisis de una base de datos relacionada con tu tema de tesis, la estructura del proyecto es adecuada y visualizaciones me parecieron acertadas además de haber utilizado distintas librerías de visualización de acuerdo al tipo de gráfica que presentas en cada caso. ¡Muy buen esfuerzo y muchas felicidades!

### Ligas
- [LINK DE PROYECTO
](https://github.com/edd885/Tecnicas-de-machine-learning-en-an-lisis-de-resultados-de-laboratorio)

- [DIVULGACIÓN: LinkedIn](https://www.linkedin.com/feed/update/urn:li:activity:7253948961156169728)

Saludos,
Víctor Cuspinera

**Comment by edd885** [comment]
Gracias por las correcciones y observaciones profesor. 

- Ya corregí la desripción del readme principal, por una más decriptiva.
- Agregué en la descripción, que ahora están los archivos de streamlit también en el README principal
- en el CITATION también corregí por el nombre correcto, ya que usaba uno que no tenía relación.
- Modifiqué la ruta de file_path como fue sugerido

En la versión final crearé los nombres y descripciones reales. Quiero recordar que para efectos de que no aparezca algún trabajo similar publicado, quiero evitar la utilización de descripciones reales.
